name: Server-side render (SSR) with react-snap
description: This action uses react-snap to pre-render a web application into static, hydratable HTML.
inputs:
  root:
    description: The root directory of your application (where package.json is)
    required: false
    default: .
  output:
    description: The name of the output folder of your bundled application, within the above directory
    required: false
    default: dist
branding:
  icon: camera
  color: yellow
runs:
  using: composite
  steps:
  - name: Checkout 🛎️
    uses: actions/checkout@v3

  - name: Set up environment for Puppeteer
    shell: bash
    run: |
      sudo apt-get update
      sudo apt-get install -y libx11-6 libxcomposite1 libxcursor1 libxdamage1 libxext6 \
              libxfixes3 libxi6 libxtst6 libnss3 libglib2.0-0 libgtk-3-0t64 \
              libasound2t64 libxrandr2 libpangocairo-1.0-0 libatk1.0-0 \
              libatk-bridge2.0-0 libcups2 libdbus-1-3 libdrm2 libgbm1 \
              libgdk-pixbuf2.0-0
  
  - name: Install dependencies and build 🔧
    shell: bash
    working-directory: ${{ inputs.root }}
    run: |
      npm install react-snap
      npm run build

  - name: Add react-snap configuration
    id: info
    uses: jaywcjlove/github-action-package@main
    with:
      path: ${{ inputs.root }}/package.json
      data: |
        {
          "reactSnap": {
            "source": "${{ inputs.output }}",
            "puppeteerArgs": [
              "--no-sandbox",
              "--disable-setuid-sandbox",
              "--disable-dev-shm-usage",
              "--single-process"
            ]}
        }

  - name: Pre-render application
    shell: bash
    working-directory: ${{ inputs.root }}
    run: npx react-snap
